# Generated by Django 5.2.4 on 2025-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
